### ISSUE TITLE
error on mac

### ISSUE THREAD

**Issue by arifintajul4** [wibucrypto2201/autorevox#2]
<img width="1093" alt="Screenshot 2024-07-09 at 11 50 13" src="https://github.com/wibucrypto2201/autorevox/assets/36062540/c9ac6b61-c898-4eb2-a279-604e70c10185">
I am using mac m1, and get error like this

**Comment by arifintajul4** [comment]
solved remove ua = UserAgent() line 50

**Comment by wibucrypto2201** [comment]
find me in https://t.me/wibuairdrop142
